"""
UTKFace dataset loader for PyTorch.

This module provides a PyTorch Dataset class for loading UTKFace images
with age and gender labels for multitask learning.
"""

import os
from pathlib import Path
from typing import Optional, List, Callable

import pandas as pd
import numpy as np
from PIL import Image
import torch
from torch.utils.data import Dataset


class UTKFaceDataset(Dataset):
    """PyTorch Dataset for UTKFace with age regression and gender classification.
    
    Args:
        metadata_path: Path to metadata CSV file (generated by notebook 01)
        image_dir: Root directory containing UTKFace images
        split_indices: Optional list of indices to filter dataset (for train/val/test splits)
        transform: Optional image transformation pipeline
        
    Returns:
        Tuple of (image, age, gender) where:
            - image: torch.Tensor of shape (3, H, W)
            - age: float (regression target)
            - gender: float (0.0 or 1.0 for binary classification)
    """
    
    def __init__(
        self, 
        metadata_path: str,
        image_dir: str,
        split_indices: Optional[List[int]] = None,
        transform: Optional[Callable] = None
    ):
        self.metadata_path = Path(metadata_path)
        self.image_dir = Path(image_dir)
        self.transform = transform
        
        # Load metadata
        self.metadata = pd.read_csv(self.metadata_path)
        
        # Filter by split indices if provided
        if split_indices is not None:
            self.metadata = self.metadata.iloc[split_indices].reset_index(drop=True)
        
        # Validate required columns
        required_cols = ['filename', 'age', 'gender']
        missing_cols = set(required_cols) - set(self.metadata.columns)
        if missing_cols:
            raise ValueError(f"Metadata missing required columns: {missing_cols}")
        
    def __len__(self) -> int:
        return len(self.metadata)
    
    def __getitem__(self, idx: int):
        """Get a single sample."""
        row = self.metadata.iloc[idx]
        
        # Load image
        img_path = self.image_dir / row['filename']
        try:
            image = Image.open(img_path).convert('RGB')
        except Exception as e:
            raise IOError(f"Failed to load image {img_path}: {e}")
        
        # Extract labels
        age = float(row['age'])
        gender = float(row['gender'])  # 0 or 1
        
        # Apply transformations
        if self.transform:
            # Albumentations expects numpy array
            image_np = np.array(image)
            transformed = self.transform(image=image_np)
            image = transformed['image']
        else:
            # Convert to tensor manually if no transform provided
            image = torch.from_numpy(np.array(image)).permute(2, 0, 1).float() / 255.0
        
        return image, age, gender
    
    def get_label_statistics(self):
        """Get dataset statistics for stratification."""
        return {
            'age_mean': self.metadata['age'].mean(),
            'age_std': self.metadata['age'].std(),
            'age_min': self.metadata['age'].min(),
            'age_max': self.metadata['age'].max(),
            'gender_counts': self.metadata['gender'].value_counts().to_dict(),
            'total_samples': len(self.metadata)
        }
